# Generated by Django 4.1.7 on 2023-04-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('34 (XS)', '34 (XS)'), ('36 (XS)', '36 (XS)'), ('38 (M)', '38 (M)'), ('40 (M)', '40 (M)'), ('42 (L)', '42 (L)'), ('44 (L)', '44 (L)'), ('46 (XL)', '46 (XL)'), ('48 (XL)', '48 (XL)')], max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(to='products.size'),
        ),
    ]
