# Generated by Django 4.1.7 on 2023-08-10 15:58

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import services.uploader


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_comment_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=200)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('desc', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=services.uploader.Uploader.upload_image_blog)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.blog')),
            ],
            options={
                'verbose_name': 'Blog Gallery',
                'verbose_name_plural': 'Blog Galleries',
                'ordering': ('created_at',),
            },
        ),
    ]
