# Generated by Django 4.1.7 on 2023-08-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_blog_alter_product_weight_blogimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_stock', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
