# Generated by Django 4.1.7 on 2023-08-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_composition_alter_size_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Qırmızı', 'Qırmızı'), ('Mavi', 'Mavi'), ('Yaşıl', 'Yaşıl'), ('Qəhvəyi', 'Qəhvəyi'), ('Ağ', 'Ağ'), ('Qara', 'Qara'), ('Sarı', 'Sarı')], max_length=200),
        ),
    ]
