# Generated by Django 4.1.7 on 2023-08-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Qırmızı', 'Qırmızı'), ('Mavi', 'Mavi'), ('Yaşıl', 'Yaşıl'), ('Qəhvəyi', 'Qəhvəyi'), ('Ağ', 'Ağ'), ('Qara', 'Qara'), ('Sarı', 'Sarı'), ('Krem', 'Krem')], max_length=200),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(choices=[('26', '26'), ('28', '28'), ('30', '30'), ('32', '32'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('42', '42'), ('44', '44'), ('34 (XS)', '34 (XS)'), ('36 (XS)', '36 (XS)'), ('38 (M)', '38 (M)'), ('40 (M)', '40 (M)'), ('42 (L)', '42 (L)'), ('44 (L)', '44 (L)'), ('46 (XL)', '46 (XL)'), ('48 (XL)', '48 (XL)')], max_length=200),
        ),
    ]
