# Generated by Django 4.1.7 on 2023-08-26 05:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_color_alter_size_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
